### PR TITLE
Add shouldShowRequestPermissionRationale to Permission

### PR DESCRIPTION
**Pull request by vanniktech**
Otherwise you don't know whether the user has clicked `don't show again` or not.

If this gets approved I'll add tests.

### CODE REVIEW

**Comment by tbruyelle** [comment]
Thanks but you need to fix and update the tests.

**Comment by vanniktech** [comment]
@tbruyelle I know but I first wanted to hear whether this is a change / enhancement that is wanted or not before investing more time in tests.

**Comment by tbruyelle** [comment]
The feature has been suggested and approved in #68  :)

**Comment by vanniktech** [comment]
Alright cool maybe you can help me with the following:

Consider a button 'I allow camera permission'.

- If you press the button for the first time the normal Android Permission Dialog is shown. You deny it.
- Next time you press it you deny it again with "don't ask again'.
- Now if you press it a third time you won't get the dialog anymore because you pressed "don't ask again". The only way to enable the permission now is to go to the settings.

I'm trying to implement the above UI example and I'm having a hard time with it.

```java
rxPermissions.requestEach(Manifest.permission.CAMERA)
  .first()
  .toSingle()
  .subscribe(permission -> {
    if (!permission.shouldShowRequestPermissionRationale) {
      // Need to go to the settings
    } else if (permission.granted) {
      // All good
    } else {
      // Denied permission
    }
  });
```
 
The problem is that even the first time I click on "don't ask again" I end up in ` // Need to go to the settings` and that's not desired behavior as I only want to go into the settings the next time he presses that button.

Any thoughts on that?

**Comment by vanniktech** [comment]
I think the `shouldShowRequestPermissionRationale` check would need to be done before asking for the permission. Doing it after the permission has been allowed / denied is one step to late. What do you think?

**Comment by tbruyelle** [comment]
From https://developer.android.com/training/permissions/requesting.html
> To help find situations where the user might need an explanation, Android provides a utiltity method, shouldShowRequestPermissionRationale(). This method returns true if the app has requested this permission previously and the user denied the request.

> Note: If the user turned down the permission request in the past and chose the Don't ask again option in the permission request system dialog, this method returns false. The method also returns false if a device policy prohibits the app from having that permission.

So in your case, the first time the user denied the request, the method should returns true. Unless you have a device policy which prohibits the app from having the camera permission, or there's something wrong in your implementation (but didn't find what).

Other thing, I think you should check if permission is granted first, because in that case it's possible that `shouldShowRequestPermissionRationale` returns false.

**Comment by vanniktech** [comment]
What works for me now is doing the work of the `shouldShowRequestPermissionRationale` array in `handleIntent()` instead. Basically before requesting I check the rationale status for every permission.

**Comment by tbruyelle** [comment]
That's weird because that's not what the documentation say...

> This method returns true if the app has requested this permission **previously** and the user denied the request.

Moreover on my app I get the expected result by invoking that method *after* I request the persmissions (I use `RxPermissions.shouldShowRequestPermissionRationale()`)

**Comment by vanniktech** [comment]
Maybe the documentation is wrong?

Executing `shouldShowRequestPermissionRationale` after the permission:

- If you press the button for the first time the normal Android Permission Dialog is shown. You deny it. **returns true**
- Next time you press it you deny it again with "don't ask again'. **returns false**
- Now if you press it a third time you won't get the dialog anymore because you pressed "don't ask again". The only way to enable the permission now is to go to the setting **returns false**

Executing `shouldShowRequestPermissionRationale` before the permission:

- If you press the button for the first time the normal Android Permission Dialog is shown. You deny it. **returns true**
- Next time you press it you deny it again with "don't ask again'. **returns true**
- Now if you press it a third time you won't get the dialog anymore because you pressed "don't ask again". The only way to enable the permission now is to go to the setting **returns false**

I'd argue that this is expected behavior.

**Comment by tbruyelle** [comment]
The behavior you described for *after the permission* sounds correct to me, and fit the documention. Is it what you experienced with your case ?

**Comment by vanniktech** [comment]
Yup that is the one. `after` does not work for my use case. `before` does. Now the question is which should be implemented in the library? I'm voting for the `before` case however others may have a different opinion.

**Comment by tarasantoshchuk** [comment]
@vanniktech @tbruyelle 

From my experience `shouldShowRequestPermissionRationale` has following behaviour:

1. before the first time we asked for permission, **it returns false**
2. if we already asked user for permission and he denied it, **but didn't check** "Never ask again", **it return true**
3. if user once denied permission request with "Never ask again" checked, **it returns false**
4. if permission is already granted, **it returns false**

What this behaviour means for us:

1. `shouldShowRequestPermissionRationale` returns false **AND** we already asked for permission **AND** permission was denied **is the only condition** when we can tell for sure that user denied permission with "Never ask again" checked
2. from 1 follows, that we **must** check if user denied permissions forever **after** permission request, because before permission request, value returned by 'shouldShowRequest...', is ambiguous for us.

**Comment by vanniktech** [comment]
Well it's not ambiguous before the request. If you have checked "don't ask again" you'll still end up in `onPermissionResult` and will get a granted of `false`. 

Plus the first time it may be that `shouldShowRequest` is false which is not wanted however you can't choose "don't ask again" the first time.

**Comment by tbruyelle** [comment]
By doing it *before* we break what most users will expect from that value.

@vanniktech So you want to know when the user has clicked on "Never ask again", that's simple, the code below should work with the *after* way : 

```java
.subscribe(permission -> {
    if (permission.granted)  {
      // All good
    } else if (permission.shouldShowRequestPermissionRationale)
      // Denied permission without ask never again
    } else {
      // Denied permission with ask never again      
      // Need to go to the settings
    }
  });
```

That's currently what I do in my app and it works like a charm.

**Comment by tarasantoshchuk** [comment]
> Well it's not ambiguous before the request. If you have checked "don't ask again" you'll still end up in onPermissionResult and will get a granted of false.

And if call 'shouldShowRequest...' before request and it returns false, it may be that user denied permission with "don't ask again", but it also may be that we never requested this permission before

**Comment by tarasantoshchuk** [comment]
@tbruyelle 
also we should rename Permission#shouldShowRequestPermissionRationale to something like Permission#deniedForever. This way the meaning of the field will be obvious for user.

**Comment by vanniktech** [comment]
@tbruyelle If you just pressed the deny button and checked "don't ask again" I don't want to navigate the user into the settings. However if the user comes back and then presses that button and the Android Dialog can't be shown anymore since the user pressed "don't ask again" then I need to navigate the user into the settings.

**Comment by tbruyelle** [comment]
> also we should rename Permission#shouldShowRequestPermissionRationale to something like Permission#deniedForever. This way the meaning of the field will be obvious for user.

I disagree, by keeping the name we don't have to maintain an extra documentation. Users should know about `shouldShowRequestPermissionRationale`.

**Comment by tbruyelle** [comment]
@vanniktech 
> If you just pressed the deny button and checked "don't ask again" I don't want to navigate the user into the settings. However if the user comes back and then presses that button and the Android Dialog can't be shown anymore since the user pressed "don't ask again" then I need to navigate the user into the settings.

Why having a separate behavior between the first time the user denied with "don't ask again" and the second time ?

Both time you should display a snackbar or something like that, telling him he have to go to the settings if he finally changes his mind, with a button that brings him to the settings.

**Comment by vanniktech** [comment]
Well because that separate behavior is wanted and with asking `before` the permission you are able to do that.

Maybe both values should be taken into permission. The value before asking the permission and the value after the user did that.

**Comment by tbruyelle** [comment]
> Maybe both values should be taken into permission. The value before asking the permission and the value after the user did that.

Nope I don't want that. The expected behavior according to the android documentation is to invoke `shouldShowRequestPermissionRationale` after a request, not before. Moreover this will be horrible with variable name like `*before` and `*after`.

You'll have to add extra code in your app to handle your case.

```

**Comment by vanniktech** [comment]
Alright fair enough. Though adding this extra code is super clunky as I need to get a reference to an Activity after that permission request is done and check that state and then I also need to persist it because otherwise I can't differentiate between the events.

I'll just stick with my fork and have a local copy of this library with the modification that I need then.

**Comment by tbruyelle** [comment]
I read your sample code again, and even with the *before* way, I'm not sure this will fit your need because `shouldShowRequestPermissionRationale` can return false in 3 cases : 

- user clicks on never ask again
- permission has never been asked
- permission is already granted

```java
rxPermissions.requestEach(Manifest.permission.CAMERA)
  .first()
  .toSingle()
  .subscribe(permission -> {
    if (!permission.shouldShowRequestPermissionRationale) {
      // Need to go to the settings
      // Or the permission has never been asked
      // Or the permission is already granted
    } else if (permission.granted) {
      // All good
    } else {
      // Denied permission
    }
  });
   
})
```

**Comment by vanniktech** [comment]
The thing is though that when you request the permission for the first time you'll always get a response back (either granted or not granted). Also the first time I still get `shouldShowRequestPermissionRationale=true`

**Comment by vanniktech** [comment]
Plus it's probably smarter to do the `if (granted)` check first so that `shouldShowRequestPermissionRationale` does not go into our way.

**Comment by thekalinga** [comment]
Any planned to closure on this issue? This has been sitting idle for quite sometime now.

**Comment by vanniktech** [comment]
Not from my side. I'll leave it up to the repo owners. Also I'm now using RxPermissions with Rx2 support containing this in my own fork. (Distributed via jitpack for now)

**Comment by thekalinga** [comment]
Does it work with Rx 1.+ as well?

**Comment by vanniktech** [comment]
Nope moved away from Rx1

**Comment by tbruyelle** [comment]
I merged your PR but moved the `shouldShowRequestPermissionRationale` invocation after the `requestPermissions`. Thanks for the contribution.

**Pull request closed without merging**
