### PR TITLE
Replace ShadowActivity by Fragment.

### LINKED ISSUE #44: Ask permission again
Once the user denies permission, re-asking it doesn't show up the dialog to allow or deny.
I need to restart the application to make it appear again.

Is it by design? Or I'm missing something ?

``` java
RxPermissions.getInstance(context)
    .request(Manifest.permission.ACCESS_FINE_LOCATION)
    .subscribe(..)
```

### PR DESCRIPTION
**Pull request by epool**
- Replace `ShadowActivity` in favor of retained fragment.
- Fixes #44.
- Update dependencies.
- Remove IDE warnings.
- Add [Robolectric](http://robolectric.org/) for testing purpose.

### CODE REVIEW

**Comment by tbruyelle** [comment]
Sounds cool. Can you explain what the benefit of using a retained fragment, and what are the rotating screen issues you fixed ?

**Comment by epool** [comment]
@tbruyelle I was getting a issue on the emulator, when I tap on request permission and permission dialog was shown and then I rotate the display and accept the permission the application demo was crashing.

The benefit of `setRetainInstance(true);` is that the fragment will live along with the activity even after rotation, so once the activity is recreated the fragment still alive and re-attached to the new activity, so no more rotation issues. Without this the fragment dies along with the activity and the permission request process is lost.

**Comment by tbruyelle** [comment]
Fine, I had to do some tests.

**Comment by epool** [comment]
@tbruyelle sure feel free to suggest me changes.

**Comment by tbruyelle** [comment]
Sorry for the delay. 

I briefly started some tests and first of all I got a crash in the sample app, when I return to the sample app after tweaking the app permissions in the settings. `RxPermissions.getInstance` returned null so a NPE raised. 

It seems there's a bug in the  `newInstance` detection.

To reproduce : 
- open the Sample app
- Open the sample app in the settings and update the permissions
- return to the Sample app -> crash

**Comment by epool** [comment]
@tbruyelle I just fixed the NPE and moved all the permissions state from `RxPermissions` to `RxPermissionsFragment` since it is a retained fragment and the singleton on `RxPermissions` is no more required.

**Comment by tbruyelle** [comment]
Ok since you moved the subjects list in the fragment, there's no need to have `RxPermissions.onRequestPermissionResults()`, everything can be done in the fragment if I'm right.

I'm still testing.

**Comment by tbruyelle** [comment]
Another issue, if you invoke `requestEach` directly in your activity `onCreate`, there's a crash because `RxPermissionsFragment.getActivity()` returns null. It seems the fragment is not yet attached to the activity at this time (aahh that's why I love fragment...)

To reproduce, change the sample app `MainActivity` like that : 

```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final RxPermissions rxPermissions = RxPermissions.newInstance(this);
        rxPermissions.setLogging(true);

        setContentView(R.layout.act_main);
        surfaceView = (SurfaceView) findViewById(R.id.surfaceView);

                rxPermissions.requestEach(Manifest.permission.CAMERA)
                        .subscribe(new Action1<Permission>() {
                                       @Override
                                       public void call(Permission permission) {
                                           Log.i(TAG, "Permission result " + permission);
                                           if (permission.granted) {
                                               Toast.makeText(MainActivity.this,
                                                       "Camera permission granted",
                                                       Toast.LENGTH_SHORT).show();
                                               releaseCamera();
                                               camera = Camera.open(0);
                                               try {
                                                   camera.setPreviewDisplay(surfaceView.getHolder());
                                                   camera.startPreview();
                                               } catch (IOException e) {
                                                   Log.e(TAG, "Error while trying to display the camera preview", e);
                                               }
                                           } else if (permission.shouldShowRequestPermissionRationale) {
                                               // Denied permission without ask never again
                                               Toast.makeText(MainActivity.this,
                                                       "Denied permission without ask never again",
                                                       Toast.LENGTH_SHORT).show();
                                           } else {
                                               // Denied permission with ask never again
                                               // Need to go to the settings
                                               Toast.makeText(MainActivity.this,
                                                       "Permission denied, can't enable the camera",
                                                       Toast.LENGTH_SHORT).show();
                                           }
                                       }
                                   },
                                new Action1<Throwable>() {
                                    @Override
                                    public void call(Throwable t) {
                                        Log.e(TAG, "onError", t);  // <--- crash is reported here
                                    }
                                },
                                new Action0() {
                                    @Override
                                    public void call() {
                                        Log.i(TAG, "OnComplete");
                                    }
                                });
}

```

**Comment by epool** [comment]
@tbruyelle Issue fixed, thanks for taking your time for testing that scenarios. 😄

**Comment by tbruyelle** [comment]
Np, the PR is promising, I hope it can remove the biggest drawback of the library : having to subscribe during the init phase.

**Comment by epool** [comment]
@tbruyelle let me know if you need any change for  this PR please.

**Comment by tbruyelle** [comment]
Sure, for the moment I try to find the time to complete the tests, sry for
the delay.

**Comment by epool** [comment]
@tbruyelle not sure but looks like this PR could fix #96 also.

**Comment by tbruyelle** [comment]
I completed some tests about config change and it's ok. 
Now I'm worried about the breaking change you introduced by removing the hability to get the singleton instance of `RxPermissions`. Is it really necessary ?

Other subject, the changes need to ported also in the `2.x` branch, and that's a boring job.

**Comment by epool** [comment]
@tbruyelle I can rollback the renaming from `RxPermissions.newInstance(activity)` to `RxPermissions.getInstance(activity)` if you prefer, but it is getting a new instance just the fragment is acting as singleton, but if you prefer I can name it `RxPermissions.getInstance()` back again.

Regarding `2.x` I can create a new branch from `2.x`, apply these changes on that branch and create another PR against `2.x` branch.

**Comment by tbruyelle** [comment]
> I can rollback the renaming from RxPermissions.newInstance(activity) to RxPermissions.getInstance(activity)

That would break the contract because as you said it's no more a singleton. I prefer to have a simple constructor rather than `newInstance`.

> Regarding 2.x I can create a new branch from 2.x, apply these changes on that branch and create another PR against 2.x branch.

Great, let's do this. Thanks in advance

**Comment by epool** [comment]
@tbruyelle should we wait for `2.x` implementation for merging this PR?

**Comment by tbruyelle** [comment]
Well I'm not sure, wdyt?

**Comment by epool** [comment]
@tbruyelle actually I would prefer to merge this PR and release this PR in an independent way of the `2.x` version. But it's up to you take the decision.

**Comment by tbruyelle** [comment]
Ok let's merge it

**Comment by tbruyelle** [comment]
Ready in version 0.9.0 (not 0.8.3 because of the breaking change)

**Comment by tbruyelle** [comment]
And thanks for the awesome work!

**Comment by epool** [comment]
@tbruyelle NP actually I was planing to create a library like this one, but I didn't know about `RxPermissions` but when I know it I better decided to create this PR 😃 . BTW I think the git release tagging is pending for `9.0.0` version.

**Pull request merged**
