### PR TITLE
Upload to bintray

### PR DESCRIPTION
**Pull request by nhpatt**
Scripts and configuration to upload to bintray with a valid pom (and be able to link it with jcenter())

it needs 2 properties, bintray.user and bintray.apikey in local.properties.

I had to change the local name of the lib folder when importing in gradle because the script kept exporting 'lib' but I don't think it's an extreme change (it should* exist another way to do it).

### CODE REVIEW

**Comment by tbruyelle** [comment]
Thanks for that, but I didn't manage to upload an artifact.

First I fixed the package name (see 08b227cea808ca9fcf6d8b3e499c8488c6337c87)

I filled my bintray user and api key, generated the pom and jar with the `install` task (maybe there's a task which do not copy the files in `~/.m2` ?), and tried to upload with `bintrayUpload` task. It returns me success but then I can't find the artifact in jcenter.

If I rerun `bintrayUpload` I got an error telling me the artifact already exists.

```sh
* What went wrong:
Execution failed for task ':rxpermissions:bintrayUpload'.
> Could not upload to 'https://api.bintray.com/content/tbruyelle/tbruyelle/RxPermissions/0.5.2/com/tbruyelle/rxpermissions/rxpermissions/0.5.2/rxpermissions-0.5.2.aar': HTTP/1.1 409 Conflict [message:Unable to upload files: An artifact with the path 'com/tbruyelle/rxpermissions/rxpermissions/0.5.2/rxpermissions-0.5.2.aar' already exists]
```

**Comment by nhpatt** [comment]
Sorry I didn't explain the process :(

You can do directly a gradlew bintrayUpload and will generate the pom and jar and upload it directly. The correct route is this one: https://bintray.com/tbruyelle/tbruyelle/RxPermissions/0.5.2/view#files/com/tbruyelle/rxpermissions/0.5.2 (those are in the correct folder).

The first time (and that's the step missing), you have to link your repo with jcenter, here in linked to, add to jcenter. Just fill the form in usually in a few hours will be available :)

This POM is in the wrong place: https://bintray.com/tbruyelle/tbruyelle/RxPermissions/0.5.2/view#files/com/tbruyelle/rxpermissions/rxpermissions/0.5.2 and I think that's the strange behaviour of the lib/rxpermissions folder.

**Comment by tbruyelle** [comment]
> The first time (and that's the step missing), you have to link your repo with jcenter, here in linked to, add to jcenter. Just fill the form and usually in a few hours will be available :)

Ok thanks I did'nt know that.



> You can do directly a gradlew bintrayUpload and will generate the pom and jar and upload it directly.

Well, I'm not sure : 

```bash
$ ./gradlew clean rxpermissions:bintrayUpload
Parallel execution with configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:rxpermissions:clean
:sample:clean UP-TO-DATE
:rxpermissions:clean UP-TO-DATE
:rxpermissions:bintrayUpload:rxpermissions:bintrayUpload: file /home/tbruyelle/projects/rxpermissions/lib/build/libs/rxpermissions-0.5.2-javadoc.jar could not be found.
:rxpermissions:bintrayUpload: file /home/tbruyelle/projects/rxpermissions/lib/build/libs/rxpermissions-0.5.2-sources.jar could not be found.
:rxpermissions:bintrayUpload: file /home/tbruyelle/projects/rxpermissions/lib/build/outputs/aar/rxpermissions-release.aar could not be found.
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rxpermissions:bintrayUpload'.
> java.io.FileNotFoundException: /home/tbruyelle/projects/rxpermissions/lib/build/poms/pom-default.xml (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by nhpatt** [comment]
I've pushed a commit to force downloading the latest platform that (I think) was causing the travisci error because of lint.

It's strange that _./gradlew bintrayUpload_ doesn't work on your machine before generating the pom and jar before :( I've tried in my machine and with parallel enabled and that target calls to generate the jar/pom (tried also deleting the files)...

Did you try to link with jcenter? I haven't seen the files so I suppose something went wrong :( did they respond with any problems? I'm willing to help in whatever you need :)

**Comment by nhpatt** [comment]
Do you need help? I can try to clarify whatever you want :)

**Comment by tbruyelle** [comment]
Well sorry I'm still stuck because there's no pom/jar generated with the `bintrayUpload` task.

Can you test again with the `jcenter` branch of that repo ?

**Comment by nhpatt** [comment]
I've tested the jcenter branch with a fresh clone with my computer and in a colleague's computer with my local.properties (against this repo: https://bintray.com/nhpatt/tbruyelle/RxPermissions/) and seems to work fine.

I'll enumerate the steps I followed:

- I remove the 0.52 version from bintray (because if not I received a "HTTP/1.1 409 Conflict [message:Unable to upload files..."
- I execute "./gradlew bintrayUpload" in the repository root (you don't have to be in the library folder or specify the library project) and automatically creates the aar and the jar for the sources and uploads them to bintray.

I'm a bit lost about why it could be failing in your machine, can you post the full stacktrace of the error? I tried before with the parallel computation. The stack you posted is missing a lot of steps, do you have a specific gradle configuration?

Can you try "./gradlew bintrayUpload" in the root of the repository or in a new cloned repo?

**Comment by tbruyelle** [comment]
Thank you for you time, I finally find the problem I have on my machine it's because my gradle.properties has the following feature enabled : `org.gradle.configureondemande`. If I disable it the pom and jars are correctly generated. Don't ask me why I enabled this feature, I can't remember !!

So I managed to upload the artifact to bintray and I asked a link to jcenter. Wait and see ^^

**Comment by nhpatt** [comment]
Great :) Let's hope everything is fine :D

**Comment by tbruyelle** [comment]
Ok so my repo is still not linked, this is probably because only version 0.5.2 has the requirements for jcenter linkability (pom and jar stuff).

I can't delete old versions because other people may use them, so I have 2 options

- manually add bintrayUplload functionnality to each tags (should take some time...)
- create an other repo with only version 0.5.2 (but I'll loose all my repo stats and at next version some users will complain about missing artfiact because they have kept the original repo).

Short, this is annoying... Maybe you have better idea ?

**Comment by nhpatt** [comment]
I'm afraid not.

I can generate the source jars for the other versions and send them to you (should be apply those commits after the tags of each version and generate).

Sometimes it takes more to link and they send you a notification in bintray when they've finished, I would wait at least a day, hopefully they can link just from 0.5.2 version...

**Comment by tbruyelle** [comment]
> I can generate the source jars for the other versions and send them to you (should be apply those commits after the tags of each version and generate).

You're nice, but that's fine thank you. I will do it if necessary. I'll wait tomorrow.

**Comment by nhpatt** [comment]
I saw that you uploaded all the versions (sorry for the troubles) and the library is now synced (https://jcenter.bintray.com/com/tbruyelle/rxpermissions/rxpermissions/).

Thank you very much! :)

**Comment by tbruyelle** [comment]
It's me who thank you for the contribution, I merged the `jcenter` branch so this PR can be closed.

**Pull request closed without merging**
