### PR TITLE
fixed status bar and navigation bar colors

### PR DESCRIPTION
**Pull request by RonTt**
I found small bug in UI. I'm using custom color for status and navigation bars in application theme. But when showing dialog I see black color in these bars. 
Also if I denied permission with "Never ask again" I'll see blinking status bar on every touch on button which request permissions (e.g. "Enable camera" in sample).
Fix for it is in my request.

### CODE REVIEW

**Comment by tbruyelle** [comment]
Thanks for the PR but the problem is now probably fixed in version 0.9.0, where we don't use activities any more. Could you check ?

**Comment by epool** [comment]
@RonTt Could you try the latest `9.0.0` version please? probably this new release fixed this issue.

**Comment by RonTt** [comment]
@epool @tbruyelle I've checked version 0.9.0, issue is fixed. But now library has lost one important (for me) function. Previous version required context only, now - requires activity. I don't have activity for checking permissions (I'm using it from service).

**Comment by tbruyelle** [comment]
Well sorry but as `requestPermissions()` is a method attached to an `Activity` (and not a `Context`) I don't feel bad about requesting an Activity for the constructor argument.

**Pull request closed without merging**
