### PR TITLE
Add 'Issue template' and 'Bug report template'

### PR DESCRIPTION
**Pull request by mrArtCore**
Add 'bug report' and 'feature' templates. From now users who want to open a new issue
will be asked to fill down some template in order to give a comprehensive information
about some bug or another code defect.
Also, the user will be asked first to chose one of 2 options
 - create a Bug report
 - create a Feature request

### CODE REVIEW

**Comment by mrArtCore** [comment]
Hi @tbruyelle 
How are you?
I've created **bug** and **feature** templates for new issues. If somebody wants to open a new Issue he/she must fill down issue template. 
I create this because I've been seeing so many ugly issue reports here. And I feel guilty about doing it only now. I've experimented with this about a year ago and just had no time to do it at once then. But maybe it's not too late to create such PR?
Current flow will be:
- Click on 'New Issue'
- Choose between bug report or feature request 
- Fill down the chosen form. 

My suggestion force the community to create well-described issues so that it could be reproduced and fixed afterward.  Sometimes I feel that I can fix something, but play with reproducing things is not what I want to do. I think you know what I mean.

Note: I wasn't able to test it before merging in master (in the forked repository). So if you want to play with it and check how it works, you should fork to the private repo in another GitHub account ??? Actually I don't know how to test it if you're repo owner =\ Sorry

**Comment by mrArtCore** [comment]
@epool Hi!
Could you review my PR, please?

**Comment by mrArtCore** [comment]
@tbruyelle Hello! Hope you're going well! 
Seems that we can't reach out @epool quite a long time since PR was opened.

How about merging this without his approval?

**Comment by tbruyelle** [comment]
Yes let's merge it.

**Pull request merged**
