### PR TITLE
Add check for isPermissionRevokedByPolicy, #23

### PR DESCRIPTION
**Pull request by eleventigers**
Users should not be bothered with a permission request dialog which will always be negated by a revoked permission policy. This PR ads a check to make sure that a policy is not automatically denying a permission before issuing a permission request.

More info on the difference between `isPermissionRevokedByPolicy` an `shouldShowRequestPermissionRequestRationale` [here](https://code.google.com/p/android-developer-preview/issues/detail?id=3186#c2).

### CODE REVIEW

**Comment by tbruyelle** [comment]
Very clean PR thanks !

**Comment by tbruyelle** [comment]
Is there a reason why you put variadic parameters to `isRevoled` ? (other than replicating `isGranted`'s signature)

I'm asking you that because in the current code state there's no good reason to use variadic parameters for both `isResolved` and `isGranted`. I would like to change that and use a standard parameter, a permission.

**Comment by eleventigers** [comment]
@tbruyelle it was merely to match the current API but yes, I agree, variadics should not be used here. Hopefully you can resolve this with the next major bump ;]

**Comment by tbruyelle** [comment]
I will :)

**Comment by tbruyelle** [comment]
0.5.0 deployed with your PR and without variadic param.

**Comment by eleventigers** [comment]
Awesome, thanks!

**Pull request merged**
