### PR TITLE
android:noHistory="true"

### PR DESCRIPTION
**Pull request by zhengzhou**
if user choose the activity from history, it'll crash

### CODE REVIEW

**Comment by tbruyelle** [comment]
Can you explain a little bit the steps to reproduce ?

**Comment by zhengzhou** [comment]
after request permission, i just choose the activity from recently use, and it crash.

com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.

 Caused by: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
: 	at com.tbruyelle.rxpermissions.b.a(RxPermissions.java:286)
: 	at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:32)

**Comment by tbruyelle** [comment]
Thanks, sorry for the delay I will probably check that on next week.

**Comment by tbruyelle** [comment]
I don't see the `ShadowActivity` in the recent apps, how do you see it ?

**Comment by zhengzhou** [comment]
@tbruyelle , my activity is a launcher(android:excludeFromRecents="true"), so i can see it.

**Comment by tbruyelle** [comment]
Ok so you're talking about your app activity. In that case can you reproduce the case with the sample app ?

**Pull request closed without merging**
