### PR TITLE
Fix RxView.clicks return type in README

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by tbruyelle** [comment]
Thanks!

**Comment by vanniktech** [comment]
One question though. There's an `onDestroy` method in the RxPermissions class however it is not called in the sample app, do I need to call the `onDestroy` method or not? A little bit more information about that method would be splendid.

**Comment by tbruyelle** [comment]
As you can see, this method is not public. It's invoked internally by the `ShadowActivity`.

I document only the public API.

**Comment by vanniktech** [comment]
Oh okay my bad. Thanks! :)

**Pull request merged**
